### ISSUE TITLE
executable jar

### ISSUE THREAD

**Issue by amarzullo24** [fastcatai/fastcat#2]
Hi,
Do you plan to release an executable jar for the fastcat tool?

Thanks!

**Comment by kevits** [comment]
Hi,
thank you for asking. I noticed that I uploaded a draft release but I forgot to publish it. You can now find it under Releases within the repo: https://github.com/fastcatai/fastcat/releases
A full version (including the runtime) can be found here: [fastcat-1.0.0.zip ](https://fex.ukw.de/public/download-shares/Z0Ha7Ky4vy1lrLyD51nSDi3By5HVRalC)
Feel free to ask if you have further questions.

**Comment by amarzullo24** [comment]
Thanks for the prompt reply. Is there also a readme file with the required steps to run the program?

**Comment by kevits** [comment]
Both are executable programms. In the GitHub version you only need to add the Java runtime. I suggest you download the [zip file with runtime](https://fex.ukw.de/public/download-shares/Z0Ha7Ky4vy1lrLyD51nSDi3By5HVRalC). Then you only have to click on` faiv-1.0.0.bat`.
For other OS you are still able to execute the program via the command line which is similar as it is defined in the bat-file. When I find some time I could look into it.
